// Code generated by ogen, DO NOT EDIT.

package api

import (
	"fmt"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

func (s *ApiErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/ApiError
type ApiError struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *ApiError) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *ApiError) SetMessage(val string) {
	s.Message = val
}

// ApiErrorStatusCode wraps ApiError with StatusCode.
type ApiErrorStatusCode struct {
	StatusCode int
	Response   ApiError
}

// GetStatusCode returns the value of StatusCode.
func (s *ApiErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ApiErrorStatusCode) GetResponse() ApiError {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ApiErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ApiErrorStatusCode) SetResponse(val ApiError) {
	s.Response = val
}

type CancelOrderConflict ApiError

func (*CancelOrderConflict) cancelOrderRes() {}

type CancelOrderInternalServerError ApiError

func (*CancelOrderInternalServerError) cancelOrderRes() {}

// CancelOrderNoContent is response for CancelOrder operation.
type CancelOrderNoContent struct{}

func (*CancelOrderNoContent) cancelOrderRes() {}

type CancelOrderNotFound ApiError

func (*CancelOrderNotFound) cancelOrderRes() {}

type CreateOrderBadRequest ApiError

func (*CreateOrderBadRequest) createOrderRes() {}

type CreateOrderInternalServerError ApiError

func (*CreateOrderInternalServerError) createOrderRes() {}

// Ref: #/components/schemas/CreateOrderRequest
type CreateOrderRequest struct {
	UserUUID  uuid.UUID   `json:"user_uuid"`
	PartUuids []uuid.UUID `json:"part_uuids"`
}

// GetUserUUID returns the value of UserUUID.
func (s *CreateOrderRequest) GetUserUUID() uuid.UUID {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *CreateOrderRequest) GetPartUuids() []uuid.UUID {
	return s.PartUuids
}

// SetUserUUID sets the value of UserUUID.
func (s *CreateOrderRequest) SetUserUUID(val uuid.UUID) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *CreateOrderRequest) SetPartUuids(val []uuid.UUID) {
	s.PartUuids = val
}

// Ref: #/components/schemas/CreateOrderResponse
type CreateOrderResponse struct {
	OrderUUID  uuid.UUID `json:"order_uuid"`
	TotalPrice float64   `json:"total_price"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *CreateOrderResponse) GetOrderUUID() uuid.UUID {
	return s.OrderUUID
}

// GetTotalPrice returns the value of TotalPrice.
func (s *CreateOrderResponse) GetTotalPrice() float64 {
	return s.TotalPrice
}

// SetOrderUUID sets the value of OrderUUID.
func (s *CreateOrderResponse) SetOrderUUID(val uuid.UUID) {
	s.OrderUUID = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *CreateOrderResponse) SetTotalPrice(val float64) {
	s.TotalPrice = val
}

func (*CreateOrderResponse) createOrderRes() {}

type GetOrderInternalServerError ApiError

func (*GetOrderInternalServerError) getOrderRes() {}

type GetOrderNotFound ApiError

func (*GetOrderNotFound) getOrderRes() {}

// NewOptNilUUID returns new OptNilUUID with value set to v.
func NewOptNilUUID(v uuid.UUID) OptNilUUID {
	return OptNilUUID{
		Value: v,
		Set:   true,
	}
}

// OptNilUUID is optional nullable uuid.UUID.
type OptNilUUID struct {
	Value uuid.UUID
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilUUID was set.
func (o OptNilUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilUUID) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilUUID) SetToNull() {
	o.Set = true
	o.Null = true
	var v uuid.UUID
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilUUID) Get() (v uuid.UUID, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptOrderResponsePaymentMethod returns new OptOrderResponsePaymentMethod with value set to v.
func NewOptOrderResponsePaymentMethod(v OrderResponsePaymentMethod) OptOrderResponsePaymentMethod {
	return OptOrderResponsePaymentMethod{
		Value: v,
		Set:   true,
	}
}

// OptOrderResponsePaymentMethod is optional OrderResponsePaymentMethod.
type OptOrderResponsePaymentMethod struct {
	Value OrderResponsePaymentMethod
	Set   bool
}

// IsSet returns true if OptOrderResponsePaymentMethod was set.
func (o OptOrderResponsePaymentMethod) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptOrderResponsePaymentMethod) Reset() {
	var v OrderResponsePaymentMethod
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptOrderResponsePaymentMethod) SetTo(v OrderResponsePaymentMethod) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptOrderResponsePaymentMethod) Get() (v OrderResponsePaymentMethod, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptOrderResponsePaymentMethod) Or(d OrderResponsePaymentMethod) OrderResponsePaymentMethod {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/OrderResponse
type OrderResponse struct {
	OrderUUID       uuid.UUID                     `json:"order_uuid"`
	UserUUID        uuid.UUID                     `json:"user_uuid"`
	PartUuids       []uuid.UUID                   `json:"part_uuids"`
	TotalPrice      float64                       `json:"total_price"`
	TransactionUUID OptNilUUID                    `json:"transaction_uuid"`
	PaymentMethod   OptOrderResponsePaymentMethod `json:"payment_method"`
	Status          OrderResponseStatus           `json:"status"`
}

// GetOrderUUID returns the value of OrderUUID.
func (s *OrderResponse) GetOrderUUID() uuid.UUID {
	return s.OrderUUID
}

// GetUserUUID returns the value of UserUUID.
func (s *OrderResponse) GetUserUUID() uuid.UUID {
	return s.UserUUID
}

// GetPartUuids returns the value of PartUuids.
func (s *OrderResponse) GetPartUuids() []uuid.UUID {
	return s.PartUuids
}

// GetTotalPrice returns the value of TotalPrice.
func (s *OrderResponse) GetTotalPrice() float64 {
	return s.TotalPrice
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *OrderResponse) GetTransactionUUID() OptNilUUID {
	return s.TransactionUUID
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *OrderResponse) GetPaymentMethod() OptOrderResponsePaymentMethod {
	return s.PaymentMethod
}

// GetStatus returns the value of Status.
func (s *OrderResponse) GetStatus() OrderResponseStatus {
	return s.Status
}

// SetOrderUUID sets the value of OrderUUID.
func (s *OrderResponse) SetOrderUUID(val uuid.UUID) {
	s.OrderUUID = val
}

// SetUserUUID sets the value of UserUUID.
func (s *OrderResponse) SetUserUUID(val uuid.UUID) {
	s.UserUUID = val
}

// SetPartUuids sets the value of PartUuids.
func (s *OrderResponse) SetPartUuids(val []uuid.UUID) {
	s.PartUuids = val
}

// SetTotalPrice sets the value of TotalPrice.
func (s *OrderResponse) SetTotalPrice(val float64) {
	s.TotalPrice = val
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *OrderResponse) SetTransactionUUID(val OptNilUUID) {
	s.TransactionUUID = val
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *OrderResponse) SetPaymentMethod(val OptOrderResponsePaymentMethod) {
	s.PaymentMethod = val
}

// SetStatus sets the value of Status.
func (s *OrderResponse) SetStatus(val OrderResponseStatus) {
	s.Status = val
}

func (*OrderResponse) getOrderRes() {}

type OrderResponsePaymentMethod string

const (
	OrderResponsePaymentMethodUNKNOWN       OrderResponsePaymentMethod = "UNKNOWN"
	OrderResponsePaymentMethodCARD          OrderResponsePaymentMethod = "CARD"
	OrderResponsePaymentMethodSBP           OrderResponsePaymentMethod = "SBP"
	OrderResponsePaymentMethodCREDITCARD    OrderResponsePaymentMethod = "CREDIT_CARD"
	OrderResponsePaymentMethodINVESTORMONEY OrderResponsePaymentMethod = "INVESTOR_MONEY"
)

// AllValues returns all OrderResponsePaymentMethod values.
func (OrderResponsePaymentMethod) AllValues() []OrderResponsePaymentMethod {
	return []OrderResponsePaymentMethod{
		OrderResponsePaymentMethodUNKNOWN,
		OrderResponsePaymentMethodCARD,
		OrderResponsePaymentMethodSBP,
		OrderResponsePaymentMethodCREDITCARD,
		OrderResponsePaymentMethodINVESTORMONEY,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderResponsePaymentMethod) MarshalText() ([]byte, error) {
	switch s {
	case OrderResponsePaymentMethodUNKNOWN:
		return []byte(s), nil
	case OrderResponsePaymentMethodCARD:
		return []byte(s), nil
	case OrderResponsePaymentMethodSBP:
		return []byte(s), nil
	case OrderResponsePaymentMethodCREDITCARD:
		return []byte(s), nil
	case OrderResponsePaymentMethodINVESTORMONEY:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderResponsePaymentMethod) UnmarshalText(data []byte) error {
	switch OrderResponsePaymentMethod(data) {
	case OrderResponsePaymentMethodUNKNOWN:
		*s = OrderResponsePaymentMethodUNKNOWN
		return nil
	case OrderResponsePaymentMethodCARD:
		*s = OrderResponsePaymentMethodCARD
		return nil
	case OrderResponsePaymentMethodSBP:
		*s = OrderResponsePaymentMethodSBP
		return nil
	case OrderResponsePaymentMethodCREDITCARD:
		*s = OrderResponsePaymentMethodCREDITCARD
		return nil
	case OrderResponsePaymentMethodINVESTORMONEY:
		*s = OrderResponsePaymentMethodINVESTORMONEY
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type OrderResponseStatus string

const (
	OrderResponseStatusPENDINGPAYMENT OrderResponseStatus = "PENDING_PAYMENT"
	OrderResponseStatusPAID           OrderResponseStatus = "PAID"
	OrderResponseStatusCANCELLED      OrderResponseStatus = "CANCELLED"
)

// AllValues returns all OrderResponseStatus values.
func (OrderResponseStatus) AllValues() []OrderResponseStatus {
	return []OrderResponseStatus{
		OrderResponseStatusPENDINGPAYMENT,
		OrderResponseStatusPAID,
		OrderResponseStatusCANCELLED,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s OrderResponseStatus) MarshalText() ([]byte, error) {
	switch s {
	case OrderResponseStatusPENDINGPAYMENT:
		return []byte(s), nil
	case OrderResponseStatusPAID:
		return []byte(s), nil
	case OrderResponseStatusCANCELLED:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *OrderResponseStatus) UnmarshalText(data []byte) error {
	switch OrderResponseStatus(data) {
	case OrderResponseStatusPENDINGPAYMENT:
		*s = OrderResponseStatusPENDINGPAYMENT
		return nil
	case OrderResponseStatusPAID:
		*s = OrderResponseStatusPAID
		return nil
	case OrderResponseStatusCANCELLED:
		*s = OrderResponseStatusCANCELLED
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type PayOrderBadRequest ApiError

func (*PayOrderBadRequest) payOrderRes() {}

type PayOrderInternalServerError ApiError

func (*PayOrderInternalServerError) payOrderRes() {}

type PayOrderNotFound ApiError

func (*PayOrderNotFound) payOrderRes() {}

// Ref: #/components/schemas/PayOrderRequest
type PayOrderRequest struct {
	PaymentMethod PayOrderRequestPaymentMethod `json:"payment_method"`
}

// GetPaymentMethod returns the value of PaymentMethod.
func (s *PayOrderRequest) GetPaymentMethod() PayOrderRequestPaymentMethod {
	return s.PaymentMethod
}

// SetPaymentMethod sets the value of PaymentMethod.
func (s *PayOrderRequest) SetPaymentMethod(val PayOrderRequestPaymentMethod) {
	s.PaymentMethod = val
}

type PayOrderRequestPaymentMethod string

const (
	PayOrderRequestPaymentMethodUNKNOWN       PayOrderRequestPaymentMethod = "UNKNOWN"
	PayOrderRequestPaymentMethodCARD          PayOrderRequestPaymentMethod = "CARD"
	PayOrderRequestPaymentMethodSBP           PayOrderRequestPaymentMethod = "SBP"
	PayOrderRequestPaymentMethodCREDITCARD    PayOrderRequestPaymentMethod = "CREDIT_CARD"
	PayOrderRequestPaymentMethodINVESTORMONEY PayOrderRequestPaymentMethod = "INVESTOR_MONEY"
)

// AllValues returns all PayOrderRequestPaymentMethod values.
func (PayOrderRequestPaymentMethod) AllValues() []PayOrderRequestPaymentMethod {
	return []PayOrderRequestPaymentMethod{
		PayOrderRequestPaymentMethodUNKNOWN,
		PayOrderRequestPaymentMethodCARD,
		PayOrderRequestPaymentMethodSBP,
		PayOrderRequestPaymentMethodCREDITCARD,
		PayOrderRequestPaymentMethodINVESTORMONEY,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s PayOrderRequestPaymentMethod) MarshalText() ([]byte, error) {
	switch s {
	case PayOrderRequestPaymentMethodUNKNOWN:
		return []byte(s), nil
	case PayOrderRequestPaymentMethodCARD:
		return []byte(s), nil
	case PayOrderRequestPaymentMethodSBP:
		return []byte(s), nil
	case PayOrderRequestPaymentMethodCREDITCARD:
		return []byte(s), nil
	case PayOrderRequestPaymentMethodINVESTORMONEY:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *PayOrderRequestPaymentMethod) UnmarshalText(data []byte) error {
	switch PayOrderRequestPaymentMethod(data) {
	case PayOrderRequestPaymentMethodUNKNOWN:
		*s = PayOrderRequestPaymentMethodUNKNOWN
		return nil
	case PayOrderRequestPaymentMethodCARD:
		*s = PayOrderRequestPaymentMethodCARD
		return nil
	case PayOrderRequestPaymentMethodSBP:
		*s = PayOrderRequestPaymentMethodSBP
		return nil
	case PayOrderRequestPaymentMethodCREDITCARD:
		*s = PayOrderRequestPaymentMethodCREDITCARD
		return nil
	case PayOrderRequestPaymentMethodINVESTORMONEY:
		*s = PayOrderRequestPaymentMethodINVESTORMONEY
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/PayOrderResponse
type PayOrderResponse struct {
	TransactionUUID uuid.UUID `json:"transaction_uuid"`
}

// GetTransactionUUID returns the value of TransactionUUID.
func (s *PayOrderResponse) GetTransactionUUID() uuid.UUID {
	return s.TransactionUUID
}

// SetTransactionUUID sets the value of TransactionUUID.
func (s *PayOrderResponse) SetTransactionUUID(val uuid.UUID) {
	s.TransactionUUID = val
}

func (*PayOrderResponse) payOrderRes() {}
